### ISSUE TITLE
Incorrect repo blog link

### ISSUE THREAD

**Issue by bewestphal** [rerun-io/rerun-loader-python-example-tfrecord#6]
The "About" repo link shows `file-loaders`
<img width="328" alt="image" src="https://github.com/rerun-io/rerun-loader-python-example-tfrecord/assets/14085065/828ab411-50eb-42ed-bc1e-4e3868bbcb25">

But the blog link should be `data-loaders`?
https://rerun.io/blog/data-loaders

**Comment by teh-cmc** [comment]
Fixed, thanks
